name: API CI-CD

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - 
      name: Restore dependencies
      run: dotnet restore ./Api/InterApi/InterApi.csproj
    - 
      name: Build
      run: dotnet build --no-restore ./Api/InterApi/InterApi.csproj
    - 
      name: Publish
      run: dotnet publish ./Api/InterApi/InterApi.csproj -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Api/InterApi/Dockerfile
        push: true
        tags: |
          docker.centurionx.net/interapi
