name: API CI-CD

on:
  push:
    branches: [ master ]
    paths: Api/InterApi/
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["Api/InterApi/Deployment/appsettings.deploy.json"]'
      env:
        MYSQL_CONNECTION_STRING : ${{secrets.MYSQL_CONNECTION_STRING}}
    - name: Bash - Show XML Contents
      run: cat Api/InterApi/Deployment/appsettings.deploy.json
    - 
      name: Restore dependencies
      run: dotnet restore ./Api/InterApi/InterApi.csproj
    - 
      name: Build
      run: dotnet build --no-restore ./Api/InterApi/InterApi.csproj
    - 
      name: Publish
      run: dotnet publish ./Api/InterApi/InterApi.csproj -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Api/InterApi/Dockerfile
        push: true
        tags: |
          docker.centurionx.net/interapi
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  echo hi; #docker pull docker.centurionx.net/interapi; docker stop interapi; docker rm interapi; docker run --name interapi -e ASPNETCORE_URLS="http://+:80" -p 5001:80 --log-opt tag=api --restart=unless-stopped -d docker.centurionx.net/interapi; 
        host: ${{ secrets.HOST }}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
