name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj
    - name: Build
      run: dotnet build --no-restore ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj
    - name: Publish
      run: dotnet publish ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj -c Release -o ./app
    - name: debug
      run: ls
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    # Runs a single command using the runners shell
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./Applications/Inter.HeartbeatListenerAppService/
        file: ./Applications/Inter.HeartbeatListenerAppService/Dockerfile
        push: true
        tags: |
          docker.centurionx.net/interheartbeatlistener
