name: Heartbeat

on:
  push:
    branches: [ master ]
    paths: Applications/Inter.HeartbeatListenerAppService/
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    -
      name: Set deploy.json Target
      run: echo "deploytarget=./Applications/Inter.HeartbeatListenerAppService/Deployment/deploy.json" >> $GITHUB_ENV
    -
      name: Set appsettings.json Target
      run: echo "settingstarget=./Applications/Inter.HeartbeatListenerAppService/appsettings.json" >> $GITHUB_ENV
    - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.deploytarget}}"]'
      env:
        MYSQL_CONNECTION_STRING : ${{secrets.MYSQL_CONNECTION_STRING}}
    -
      name: Check work
      run: cat ${{env.deploytarget}}
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - 
      name: Restore dependencies
      run: dotnet restore ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj
    - 
      name: Build
      run: dotnet build --no-restore ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj
    - 
      name: Publish
      run: dotnet publish ./Applications/Inter.HeartbeatListenerAppService/Inter.HeartbeatListenerAppService.csproj -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Applications/Inter.HeartbeatListenerAppService/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          docker.centurionx.net/interheartbeatlistener
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: "docker pull docker.centurionx.net/interheartbeatlistener; docker stop heartbeatlistener; docker rm heartbeatlistener; docker run --name=heartbeatlistener --log-opt tag=heartbeatlistener --restart=unless-stopped -d docker.centurionx.net/interheartbeatlistener" 
        host: ${{ secrets.HOST }}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
