name: Plane Listener

on:
  push:
    branches: [ master ]
    paths: Applications/Inter.PlaneListener/
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - 
      name: Restore dependencies
      run: dotnet restore ./Applications/Inter.PlaneListenerService/Inter.PlaneListenerService.csproj
    - 
      name: Build
      run: dotnet build
    - 
      name: Publish
      run: dotnet publish ./Applications/Inter.PlaneListenerService/Inter.PlaneListenerService.csproj -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Applications/Inter.PlaneListenerService/Dockerfile
        push: true
        tags: |
          docker.centurionx.net/interplanelistener
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: docker pull docker.centurionx.net/interplanelistener; docker stop interplanelistener; docker rm interplanelistener; docker run --name=interplanelistener --restart=unless-stopped -d docker.centurionx.net/interplanelistener 
        host: ${{ secrets.HOST }}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
