name: Plane Ingestor CI-CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:

  build-publish:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./Applications/Inter.PlaneIngestorService
      PROJECT: Inter.PlaneIngestorService.csproj
      TAG: interplaneingestor 
    steps:
    - uses: actions/checkout@v2
    - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.REPLACESETTINGS}}"]'
      env:
        PLANEYSECURE_PASSWORD : ${{secrets.PLANEYSECURE_PASSWORD}}
        ONPREM_REDIS : ${{secrets.ONPREM_REDIS}}
        READWRITE_MYSQL : ${{secrets.READWRITE_MYSQL}}
    - 
      name: Replace Appsettings
      run: cp ${{env.WORKDIR}}/Deployment/appsettings.deploy.json ${{env.WORKDIR}}/appsettings.json
    -
      name: Check work
      run: cat ${{env.WORKDIR}}/appsettings.json

    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - 
      name: Restore dependencies
      run: dotnet restore ${{env.WORKDIR}}/${{env.PROJECT}}
    - 
      name: Build
      run: dotnet build --no-restore ${{env.WORKDIR}}/${{env.PROJECT}}
    - 
      name: Publish
      run: dotnet publish ${{env.WORKDIR}}/${{env.PROJECT}} -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ${{env.WORKDIR}}/${{env.DOCKERFILE}}
        push: true
        tags: |
          ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: ubuntu-latest
    env:
      TAG: interplaneingestor
    steps:
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; docker stop ${{env.TAG}}; docker rm ${{env.TAG}}; docker run --name ${{env.TAG}} --log-opt tag=${{env.TAG}} --restart=unless-stopped -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
        host: ${{secrets.HOST}}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    -
      name: Future Smoke Test
      run: echo ":) "
