name: Remote Log Reader CI-CD

on:
  push:
    branches: [ master ]
    paths: Applications/Inter.RemoteLogReaderService/
  workflow_dispatch:
jobs:

  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: ./Applications/Inter.RemoteLogReaderService/Dockerfile
      PROJECT: ./Applications/Inter.RemoteLogReaderService/Inter.RemoteLogReaderService.csproj
      APPSETTINGS: ./Applications/Inter.RemoteLogReaderService/appsettings.json
      REPLACESETTINGS: ./Applications/Inter.RemoteLogReaderService/Deployment/appsettings.deploy.json 
      TAG: logreader
    steps:
    - uses: actions/checkout@v2
    - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.REPLACESETTINGS}}"]'
      env:
        RABBIT_PASSWORD : ${{secrets.RABBIT_PASSWORD}}
    - 
      name: Replace Appsettings
      run: cp ${{env.REPLACESETTINGS}} ${{env.APPSETTINGS}}
    -
      name: Check work
      run: cat ${{env.APPSETTINGS}} 

    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - 
      name: Restore dependencies
      run: dotnet restore ${{env.PROJECT}}
    - 
      name: Build
      run: dotnet build --no-restore ${{env.PROJECT}}
    - 
      name: Publish
      run: dotnet publish ${{env.PROJECT}} -c Release -o ./app
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ${{env.DOCKERFILE}}
        push: true
        tags: |
          ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: ubuntu-latest
    env:
      TAG: logreader
    steps:
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; docker stop ${{env.TAG}}; docker rm ${{env.TAG}}; docker run --name ${{env.TAG}} --restart=unless-stopped -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
        host: ${{secrets.HOST}}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    -
      name: Future Smoke Test
      run: echo ":)"
